# Generated by Django 5.0.7 on 2024-10-24 20:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inputmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_visits', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('total_time_spent_on_website', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('page_views_per_visit', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('lead_origin', models.CharField(choices=[('Landing Page Submission', 'Landing Page Submission'), ('API', 'API'), ('Lead Add Form', 'Lead Add Form'), ('Lead Import', 'Lead Import')], max_length=255)),
                ('lead_source', models.CharField(choices=[('Google', 'Google'), ('Direct Traffic', 'Direct Traffic'), ('Olark Chat', 'Olark Chat'), ('Organic Search', 'Organic Search'), ('Reference', 'Reference'), ('Welingak Website', 'Welingak Website'), ('Referral Sites', 'Referral Sites'), ('Facebook', 'Facebook'), ('bing', 'bing'), ('google', 'google'), ('Click2call', 'Click2call'), ('Press_Release', 'Press_Release'), ('Social Media', 'Social Media'), ('Live Chat', 'Live Chat'), ('youtubechannel', 'youtubechannel'), ('testone', 'testone'), ('Pay per Click Ads', 'Pay per Click Ads'), ('welearnblog_Home', 'welearnblog_Home'), ('WeLearn', 'WeLearn'), ('blog', 'blog'), ('NC_EDM', 'NC_EDM')], max_length=255)),
                ('last_activity', models.CharField(choices=[('Email Opened', 'Email Opened'), ('SMS Sent', 'SMS Sent'), ('Olark Chat Conversation', 'Olark Chat Conversation'), ('Page Visited on Website', 'Page Visited on Website'), ('Converted to Lead', 'Converted to Lead'), ('Email Bounced', 'Email Bounced'), ('Email Link Clicked', 'Email Link Clicked'), ('Form Submitted on Website', 'Form Submitted on Website'), ('Unreachable', 'Unreachable'), ('Unsubscribed', 'Unsubscribed'), ('Had a Phone Conversation', 'Had a Phone Conversation'), ('View in browser link Clicked', 'View in browser link Clicked'), ('Approached upfront', 'Approached upfront'), ('Email Received', 'Email Received'), ('Email Marked Spam', 'Email Marked Spam'), ('Visited Booth in Tradeshow', 'Visited Booth in Tradeshow'), ('Resubscribed to emails', 'Resubscribed to emails')], max_length=255)),
                ('specialization', models.CharField(choices=[('Others', 'Others'), ('Finance Management', 'Finance Management'), ('Human Resource Management', 'Human Resource Management'), ('Marketing Management', 'Marketing Management'), ('Operations Management', 'Operations Management'), ('Business Administration', 'Business Administration'), ('IT Projects Management', 'IT Projects Management'), ('Supply Chain Management', 'Supply Chain Management'), ('Banking, Investment And Insurance', 'Banking, Investment And Insurance'), ('Travel and Tourism', 'Travel and Tourism'), ('Media and Advertising', 'Media and Advertising'), ('International Business', 'International Business'), ('Healthcare Management', 'Healthcare Management'), ('E-COMMERCE', 'E-COMMERCE'), ('Hospitality Management', 'Hospitality Management'), ('Retail Management', 'Retail Management'), ('Rural and Agribusiness', 'Rural and Agribusiness'), ('E-Business', 'E-Business'), ('Services Excellence', 'Services Excellence')], max_length=255)),
                ('current_occupation', models.CharField(choices=[('Unemployed', 'Unemployed'), ('Other', 'Other'), ('Working Professional', 'Working Professional'), ('Student', 'Student'), ('Housewife', 'Housewife'), ('Businessman', 'Businessman')], max_length=255)),
                ('tags', models.CharField(choices=[('No comments', 'No comments'), ('Will revert after reading the email', 'Will revert after reading the email'), ('Ringing', 'Ringing'), ('Ringing, Interested in other courses', 'Ringing, Interested in other courses'), ('Already a student', 'Already a student'), ('Closed by Horizzon', 'Closed by Horizzon'), ('switched off', 'switched off'), ('Busy', 'Busy'), ('Lost to EINS', 'Lost to EINS'), ('Not doing further education', 'Not doing further education'), ('Interested in full time MBA', 'Interested in full time MBA'), ('Graduation in progress', 'Graduation in progress'), ('invalid number', 'invalid number'), ('Diploma holder (Not Eligible)', 'Diploma holder (Not Eligible)'), ('wrong number given', 'wrong number given'), ('opp hangup', 'opp hangup'), ('number not provided', 'number not provided'), ('in touch with EINS', 'in touch with EINS'), ('Lost to Others', 'Lost to Others'), ('Still Thinking', 'Still Thinking'), ('Want to take admission but has financial problems', 'Want to take admission but has financial problems'), ('In confusion whether part time or DLP', 'In confusion whether part time or DLP'), ('Interested in Next batch', 'Interested in Next batch'), ('Lateral student', 'Lateral student'), ('Shall take in the next coming month', 'Shall take in the next coming month'), ('University not recognized', 'University not recognized'), ('Recognition issue (DEC approval)', 'Recognition issue (DEC approval)')], max_length=255)),
                ('lead_quality', models.CharField(choices=[('Not Sure', 'Not Sure'), ('Might be', 'Might be'), ('Worst', 'Worst'), ('High in Relevance', 'High in Relevance'), ('Low in Relevance', 'Low in Relevance')], max_length=255)),
                ('city', models.CharField(choices=[('Mumbai', 'Mumbai'), ('Thane & Outskirts', 'Thane & Outskirts'), ('Other Cities', 'Other Cities'), ('Other Cities of Maharashtra', 'Other Cities of Maharashtra'), ('Other Metro Cities', 'Other Metro Cities'), ('Tier II Cities', 'Tier II Cities')], max_length=255)),
                ('do_not_email', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('last_notable_activity', models.CharField(choices=[('Modified', 'Modified'), ('Email Opened', 'Email Opened'), ('SMS Sent', 'SMS Sent'), ('Page Visited on Website', 'Page Visited on Website'), ('Olark Chat Conversation', 'Olark Chat Conversation'), ('Email Link Clicked', 'Email Link Clicked'), ('Email Bounced', 'Email Bounced'), ('Unsubscribed', 'Unsubscribed'), ('Unreachable', 'Unreachable'), ('Had a Phone Conversation', 'Had a Phone Conversation'), ('Email Marked Spam', 'Email Marked Spam'), ('Approached upfront', 'Approached upfront'), ('Resubscribed to emails', 'Resubscribed to emails'), ('View in browser link Clicked', 'View in browser link Clicked'), ('Form Submitted on Website', 'Form Submitted on Website'), ('Email Received', 'Email Received')], max_length=255)),
                ('free_copy_of_mastering_the_interview', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('probability', models.FloatField(blank=True, null=True)),
                ('case', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
