# Generated by Django 5.0.7 on 2024-10-27 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadpredict', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputmodel',
            name='city',
            field=models.CharField(choices=[('Mumbai', 'Mumbai'), ('Other Cities', 'Other Cities'), ('Other Cities of Maharashtra', 'Other Cities of Maharashtra'), ('Other Metro Cities', 'Other Metro Cities'), ('Thane & Outskirts', 'Thane & Outskirts'), ('Tier II Cities', 'Tier II Cities')], max_length=255),
        ),
        migrations.AlterField(
            model_name='inputmodel',
            name='current_occupation',
            field=models.CharField(choices=[('Businessman', 'Businessman'), ('Housewife', 'Housewife'), ('Other', 'Other'), ('Student', 'Student'), ('Unemployed', 'Unemployed'), ('Working Professional', 'Working Professional')], max_length=255),
        ),
        migrations.AlterField(
            model_name='inputmodel',
            name='last_activity',
            field=models.CharField(choices=[('Approached upfront', 'Approached upfront'), ('Converted to Lead', 'Converted to Lead'), ('Email Bounced', 'Email Bounced'), ('Email Link Clicked', 'Email Link Clicked'), ('Email Marked Spam', 'Email Marked Spam'), ('Email Opened', 'Email Opened'), ('Email Received', 'Email Received'), ('Form Submitted on Website', 'Form Submitted on Website'), ('Had a Phone Conversation', 'Had a Phone Conversation'), ('Olark Chat Conversation', 'Olark Chat Conversation'), ('Page Visited on Website', 'Page Visited on Website'), ('Resubscribed to emails', 'Resubscribed to emails'), ('SMS Sent', 'SMS Sent'), ('Unreachable', 'Unreachable'), ('Unsubscribed', 'Unsubscribed'), ('View in browser link Clicked', 'View in browser link Clicked'), ('Visited Booth in Tradeshow', 'Visited Booth in Tradeshow')], max_length=255),
        ),
        migrations.AlterField(
            model_name='inputmodel',
            name='last_notable_activity',
            field=models.CharField(choices=[('Approached upfront', 'Approached upfront'), ('Email Bounced', 'Email Bounced'), ('Email Link Clicked', 'Email Link Clicked'), ('Email Marked Spam', 'Email Marked Spam'), ('Email Opened', 'Email Opened'), ('Email Received', 'Email Received'), ('Form Submitted on Website', 'Form Submitted on Website'), ('Had a Phone Conversation', 'Had a Phone Conversation'), ('Modified', 'Modified'), ('Olark Chat Conversation', 'Olark Chat Conversation'), ('Page Visited on Website', 'Page Visited on Website'), ('Resubscribed to emails', 'Resubscribed to emails'), ('SMS Sent', 'SMS Sent'), ('Unreachable', 'Unreachable'), ('Unsubscribed', 'Unsubscribed'), ('View in browser link Clicked', 'View in browser link Clicked')], max_length=255),
        ),
        migrations.AlterField(
            model_name='inputmodel',
            name='lead_origin',
            field=models.CharField(choices=[('API', 'API'), ('Landing Page Submission', 'Landing Page Submission'), ('Lead Add Form', 'Lead Add Form'), ('Lead Import', 'Lead Import')], max_length=255),
        ),
        migrations.AlterField(
            model_name='inputmodel',
            name='lead_quality',
            field=models.CharField(choices=[('High in Relevance', 'High in Relevance'), ('Low in Relevance', 'Low in Relevance'), ('Might be', 'Might be'), ('Not Sure', 'Not Sure'), ('Worst', 'Worst')], max_length=255),
        ),
        migrations.AlterField(
            model_name='inputmodel',
            name='lead_source',
            field=models.CharField(choices=[('bing', 'bing'), ('blog', 'blog'), ('Click2call', 'Click2call'), ('Direct Traffic', 'Direct Traffic'), ('google', 'google'), ('Google', 'Google'), ('Facebook', 'Facebook'), ('Live Chat', 'Live Chat'), ('NC_EDM', 'NC_EDM'), ('Olark Chat', 'Olark Chat'), ('Organic Search', 'Organic Search'), ('Pay per Click Ads', 'Pay per Click Ads'), ('Press_Release', 'Press_Release'), ('Reference', 'Reference'), ('Referral Sites', 'Referral Sites'), ('Social Media', 'Social Media'), ('testone', 'testone'), ('WeLearn', 'WeLearn'), ('welearnblog_Home', 'welearnblog_Home'), ('Welingak Website', 'Welingak Website'), ('youtubechannel', 'youtubechannel')], max_length=255),
        ),
        migrations.AlterField(
            model_name='inputmodel',
            name='specialization',
            field=models.CharField(choices=[('Banking, Investment And Insurance', 'Banking, Investment And Insurance'), ('Business Administration', 'Business Administration'), ('E-Business', 'E-Business'), ('E-COMMERCE', 'E-COMMERCE'), ('Finance Management', 'Finance Management'), ('Healthcare Management', 'Healthcare Management'), ('Hospitality Management', 'Hospitality Management'), ('Human Resource Management', 'Human Resource Management'), ('International Business', 'International Business'), ('IT Projects Management', 'IT Projects Management'), ('Marketing Management', 'Marketing Management'), ('Media and Advertising', 'Media and Advertising'), ('Operations Management', 'Operations Management'), ('Others', 'Others'), ('Retail Management', 'Retail Management'), ('Rural and Agribusiness', 'Rural and Agribusiness'), ('Services Excellence', 'Services Excellence'), ('Supply Chain Management', 'Supply Chain Management'), ('Travel and Tourism', 'Travel and Tourism')], max_length=255),
        ),
        migrations.AlterField(
            model_name='inputmodel',
            name='tags',
            field=models.CharField(choices=[('Already a student', 'Already a student'), ('Busy', 'Busy'), ('Closed by Horizzon', 'Closed by Horizzon'), ('Interested  in full time MBA', 'Interested  in full time MBA'), ('Interested in other courses', 'Interested in other courses'), ('Lost to EINS', 'Lost to EINS'), ('No comments', 'No comments'), ('Not doing further education', 'Not doing further education'), ('OTHER_COMMENT', 'OTHER_COMMENT'), ('Ringing', 'Ringing'), ('switched off', 'switched off'), ('Will revert after reading the email', 'Will revert after reading the email')], max_length=255),
        ),
    ]
